import { createElement } from '@lwc/engine-dom';
import Lwc_commu_eg1_child from 'c/lwc_commu_eg1_child';

describe('c-lwc-commu-eg1-child', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-commu-eg1-child', {
            is: Lwc_commu_eg1_child
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});