import { createElement } from '@lwc/engine-dom';
import Lwc_comm_eg1_parent from 'c/lwc_comm_eg1_parent';

describe('c-lwc-comm-eg1-parent', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-comm-eg1-parent', {
            is: Lwc_comm_eg1_parent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});